In [2]:
import torch
print(torch.__version__)

2.8.0+cu129


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")

else:
    print("GPU is not available. USing CPU")

GPU is available
Using GPU: NVIDIA GeForce RTX 4060 Laptop GPU


### Creating Tensor

In [4]:
a = torch.empty(2,3)
# empty function create space in memory, i.e allocates memory, and do not assign value on that space. only the values which are over there will get shown up.
# empty(2,3) will create 2 dimensional vector of size 2x3

In [5]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
type(a) # Tensor Object

torch.Tensor

In [7]:
# using Zeroes
b = torch.zeros(2,3)
# This makes a tensor of shape of your choice, and all values are assigned as 0.

In [8]:
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# using Ones
c = torch.ones(2,3)
# This makes a tensor of shape of your choice, and all values are assigned as 1.

In [10]:
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# using rand
d = torch.rand(2,3)
# This function makes tensor of given shape, and values are randomly assigned, with value between 0 to 1.

In [12]:
d

tensor([[0.3614, 0.7669, 0.9353],
        [0.0445, 0.1933, 0.9321]])

In [13]:
# Now if we want that same random value that we generated using rand, then we use seed.

# Means we want same output every time.

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
# custom tensor using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
# other ways

# arange
print("using arange =>", torch.arange(0,10,2)) # 0 to 10 is range and 2 is for jumping ahead of 2 numbers.
print("using arange =>", torch.arange(0,10)) # 0 to 10 is range and 2 is for jumping ahead of 2 numbers.

# using linspace
print("using linspace =>", torch.linspace(0,10,10))


# using eye
print("using eye =>", torch.eye(5)) # eye is Identity Matrix

# using full
print("using full =>", torch.full((3,3),5)) # This Means we want 3x3 matrix with each item as 5.

using arange => tensor([0, 2, 4, 6, 8])
using arange => tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace => tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye => tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full => tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#### Tensor Shapes

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)
# If humko koi existing tensor ka shape copy krna hai then use empty_like() Function. This creates new tensor with same shape as x and it has different values.

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.zeros_like(x) # This creates new tensors but all values are zeros

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x) # This creates new tensors but all values are ones.

tensor([[1, 1, 1],
        [1, 1, 1]])

In [22]:
torch.rand_like(x) # This code will not work because rand will generate float values between 0 and 1, and above we made the tensor x as all integers. so here code will not work.

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

#### Tensor Data Types

In [23]:
x.dtype # finds the datatype

torch.int64

In [24]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
torch.tensor(([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [26]:
# changing dadta type of existing tensor using  to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [27]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

### Mathematical Operations

#### 1. Scalar Operations

In [28]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [29]:
# Addition
x + 2
# Substraction
x - 2
# Multiplication
x * 3
# Division
x / 3
# int Division
(x*100)//3
# Mod
((x*100)//3)%2
# Power
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

### 2. Element Wise Operation

In [30]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [31]:
# add 
a+b

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [32]:
# subtraction
a-b

tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])

In [33]:
# multiplication 
a*b

tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])

In [34]:
# Division
a/b

tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])

In [35]:
# power
a**b

tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])

In [36]:
# mod 
a % b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [37]:
c = torch.tensor([1,-2,3,-4])

In [38]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [39]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [40]:
d = torch.tensor([1.9, 2.3, 5.6,4.5])

In [41]:
# round (round off)
torch.round(d)

tensor([2., 2., 6., 4.])

In [42]:
# ceil mein next wale integer mein chala jata hai.
torch.ceil(d)

tensor([2., 3., 6., 5.])

In [43]:
# floor mein ek integer pehele aa jata hai
torch.floor(d)

tensor([1., 2., 5., 4.])

In [44]:
# clamp se hum ek range mein numbers ko rakh skte hai.
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction Operation
Isme hum Pure ke pure number ko single number mein reduce krte hai

In [45]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [46]:
# sum of the matrix
torch.sum(e)

tensor(28.)

In [47]:
# sum along columns
torch.sum(e, dim=0) # dimension = 0 for column

tensor([14., 11.,  3.])

In [48]:
# sum along rows
torch.sum(e, dim=1) # dimension = 1 for row

tensor([15., 13.])

In [49]:
# mean
torch.mean(e) # mean only work if torch type is float

tensor(4.6667)

In [50]:
# mean along column
torch.mean(e, dim=0) # dimension = 0 for mean along column

tensor([7.0000, 5.5000, 1.5000])

In [51]:
# median
torch.median(e) 

tensor(4.)

In [52]:
torch.max(e)


tensor(9.)

In [53]:
torch.min(e)

tensor(0.)

In [54]:
torch.prod(e) # saare items ka product

tensor(0.)

In [55]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [56]:
# variance
torch.var(e)

tensor(9.8667)

In [57]:
# argmax
torch.argmax(e) # Tells the Position of the biggest item

tensor(3)

In [58]:
# argmin
torch.argmin(e) # Tells the Position of the smallest item

tensor(5)

#### 4. Matrix Operations

In [59]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [60]:
# matrix Multiplication
torch.matmul(f,g)

tensor([[116, 153],
        [166, 225]])

In [61]:
# dot products
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1, vector2)

tensor(11)

In [62]:
# transpose
f

tensor([[5, 7, 5],
        [9, 9, 7]])

In [63]:
torch.transpose(f, 0, 1) # columns ko rows bnan do

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [64]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [65]:
torch.det(h) # determinant works on square matrix

tensor(-315.)

In [66]:
# inverse
torch.inverse(h) # inverse works on square matrix

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

#### 5. Comparison Operations

In [67]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[3, 3, 5],
        [0, 6, 4]])


In [68]:
# greater than
i > j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [69]:
# less than
i < j

tensor([[False,  True,  True],
        [False, False, False]])

In [70]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [71]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [72]:
# greater than equal to
i>=j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [73]:
# less than equal to
i<=j

tensor([[False,  True,  True],
        [False, False, False]])

#### 6. Special Functions


In [74]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 8., 4.],
        [7., 2., 3.]])

In [75]:
# log
torch.log(k) # logarithm

tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [76]:
# exp
torch.exp(k) # exponents

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [77]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321]])

In [78]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [79]:
# softmax
torch.softmax(k, dim=0) # This requires element as float type

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [80]:
# relu
torch.relu(k)

tensor([[0., 8., 4.],
        [7., 2., 3.]])

#### Inplace Operations

In [81]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])
tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [82]:
m + n
# iska jo result hai vo new tensor banega in memory

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [83]:
m.add_(n)
# isse m mein hi changes hokar result m mein hi stor hoga

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [84]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [85]:
torch.relu(m)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [86]:
m.relu_()

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [87]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

#### Copying a Tensor

In [88]:
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [89]:
b = a

In [90]:
b

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [91]:
a[0][0] = 0

In [92]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [93]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [94]:
id(a)

1656660746928

In [95]:
id(b)

1656660746928

In [96]:
b = a.clone() # New Tensor formed at new location

In [97]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [98]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [99]:
a[0][0] = 10

In [100]:
a

tensor([[10.0000,  0.8935,  0.0497],
        [ 0.1780,  0.3011,  0.1893]])

In [101]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [102]:
id(a)

1656660746928

In [103]:
id(b)

1656660749488

#### Tensor Operations on GPU

In [104]:
torch.cuda.is_available()

True

In [105]:
device = torch.device('cuda')

In [106]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')