In [1]:
import torch
print(torch.__version__)

2.10.0+cpu


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")

else:
    print("GPU is not available. USing CPU")

GPU is not available. USing CPU


### Creating Tensor

In [3]:
a = torch.empty(2,3)
# empty function create space in memory, i.e allocates memory, and do not assign value on that space. only the values which are over there will get shown up.
# empty(2,3) will create 2 dimensional vector of size 2x3

In [4]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
type(a) # Tensor Object

torch.Tensor

In [6]:
# using Zeroes
b = torch.zeros(2,3)
# This makes a tensor of shape of your choice, and all values are assigned as 0.

In [7]:
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using Ones
c = torch.ones(2,3)
# This makes a tensor of shape of your choice, and all values are assigned as 1.

In [9]:
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
# using rand
d = torch.rand(2,3)
# This function makes tensor of given shape, and values are randomly assigned, with value between 0 to 1.

In [11]:
d

tensor([[0.4639, 0.9493, 0.0462],
        [0.8446, 0.6111, 0.5675]])

In [12]:
# Now if we want that same random value that we generated using rand, then we use seed.

# Means we want same output every time.

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# custom tensor using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange =>", torch.arange(0,10,2)) # 0 to 10 is range and 2 is for jumping ahead of 2 numbers.
print("using arange =>", torch.arange(0,10)) # 0 to 10 is range and 2 is for jumping ahead of 2 numbers.

# using linspace
print("using linspace =>", torch.linspace(0,10,10))


# using eye
print("using eye =>", torch.eye(5)) # eye is Identity Matrix

# using full
print("using full =>", torch.full((3,3),5)) # This Means we want 3x3 matrix with each item as 5.

using arange => tensor([0, 2, 4, 6, 8])
using arange => tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace => tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye => tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full => tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#### Tensor Shapes

In [31]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [32]:
x.shape

torch.Size([2, 3])

In [33]:
torch.empty_like(x)
# If humko koi existing tensor ka shape copy krna hai then use empty_like() Function. This creates new tensor with same shape as x and it has different values.

tensor([[0, 0, 0],
        [0, 0, 0]])

In [34]:
torch.zeros_like(x) # This creates new tensors but all values are zeros

tensor([[0, 0, 0],
        [0, 0, 0]])

In [35]:
torch.ones_like(x) # This creates new tensors but all values are ones.

tensor([[1, 1, 1],
        [1, 1, 1]])

In [37]:
torch.rand_like(x) # This code will not work because rand will generate float values between 0 and 1, and above we made the tensor x as all integers. so here code will not work.

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

#### Tensor Data Types

In [ ]:
x.dtype # finds the datatype

torch.int64

In [39]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [43]:
torch.tensor(([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [44]:
# changing dadta type of existing tensor using  to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [46]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

### Mathematical Operations

#### 1. Scalar Operations

In [47]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [51]:
# Addition
x + 2
# Substraction
x - 2
# Multiplication
x * 3
# Division
x / 3
# int Division
(x*100)//3
# Mod
((x*100)//3)%2
# Power
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

### 2. Element Wise Operation

In [52]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [53]:
# add 
a+b

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [54]:
# subtraction
a-b

tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])

In [55]:
# multiplication 
a*b

tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])

In [56]:
# Division
a/b

tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])

In [57]:
# power
a**b

tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])

In [58]:
# mod 
a % b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [59]:
c = torch.tensor([1,-2,3,-4])

In [60]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [61]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [63]:
d = torch.tensor([1.9, 2.3, 5.6,4.5])

In [64]:
# round (round off)
torch.round(d)

tensor([2., 2., 6., 4.])

In [65]:
# ceil
torch.ceil(d)

tensor([2., 3., 6., 5.])

In [66]:
# floor
torch.floor(d)

tensor([1., 2., 5., 4.])

In [67]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])