In [1]:
import torch
print(torch.__version__)

2.10.0+cpu


In [2]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")

else:
    print("GPU is not available. USing CPU")

GPU is not available. USing CPU


### Creating Tensor

In [9]:
a = torch.empty(2,3)
# empty function create space in memory, i.e allocates memory, and do not assign value on that space. only the values which are over there will get shown up.
# empty(2,3) will create 2 dimensional vector of size 2x3

In [10]:
a

tensor([[4.0711e-28, 1.5807e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
type(a) # Tensor Object

torch.Tensor

In [12]:
# using Zeroes
b = torch.zeros(2,3)
# This makes a tensor of shape of your choice, and all values are assigned as 0.

In [13]:
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
# using Ones
c = torch.ones(2,3)
# This makes a tensor of shape of your choice, and all values are assigned as 1.

In [15]:
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
# using rand
d = torch.rand(2,3)
# This function makes tensor of given shape, and values are randomly assigned, with value between 0 to 1.

In [19]:
d

tensor([[0.8830, 0.1954, 0.3997],
        [0.5995, 0.1274, 0.9351]])